appuio/component-control-api

class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, docs/modules/ROOT/partials/nav.adoc, lib/control-api.libjsonnet, tests/defaults.yml, tests/golden/defaults/control-api/control-api/20_zones.yaml
Allows to statically manage APPUiO Zones (https://kb.vshn.ch/appuio-cloud/references/architecture/control-api-zone.html)
=> Add support for managing Zones

class/control-api.yml, class/defaults.yml, tests/golden/defaults/control-api/control-api/01_crds.yaml
Allows to install and manage Control API CRDs using this component
See also #4 
=> Manage Control API CRD with component

component/api-server.jsonnet, docs/modules/ROOT/pages/how-tos/tls.adoc, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml
FIxes how-to as well as adds two flags that were necessary in production but not during testing
=> Fix setup with custom certificate

class/control-api.yml, class/defaults.yml, component/api-server.jsonnet, component/common.libsonnet, component/main.jsonnet, component/rbac-basic-user.libsonnet, component/rbac-organization.libsonnet, tests/golden/defaults/control-api/control-api/01_api_server/01_role.yaml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/01_crds.yaml, tests/golden/defaults/control-api/control-api/10_rbac_basic_user.yaml, tests/golden/defaults/control-api/control-api/10_rbac_organization.yaml, tests/golden/insecure/control-api/control-api/01_api_server/01_role.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_crds.yaml, tests/golden/insecure/control-api/control-api/10_rbac_basic_user.yaml, tests/golden/insecure/control-api/control-api/10_rbac_organization.yaml
=> Add RBAC for cloud API users

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/01_crds.yaml, tests/golden/defaults/control-api/control-api/10_rbac_basic_user.yaml, tests/golden/defaults/control-api/control-api/10_rbac_organization.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_crds.yaml, tests/golden/insecure/control-api/control-api/10_rbac_basic_user.yaml, tests/golden/insecure/control-api/control-api/10_rbac_organization.yaml
Updates Control API to https://github.com/appuio/control-api/releases/tag/v0.4.0
~This is technically a breaking change, but I propose we still make the next release `v1.3.0` as it doesn't break any of the current environments.~ Never mind let's not hide the breaking change, but I'm not going to write an upgrade guide
=> Update control API to v0.4.0

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/01_crds.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_crds.yaml
=> Update to control API `v0.5.1`

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/10_rbac_organization.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/10_rbac_organization.yaml
Fixes user permissions so that they can access teams
=> Update to control API v0.5.2

class/control-api.yml, class/defaults.yml, component/idp-adapter.libsonnet, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/defaults.yml, tests/golden/defaults/control-api/control-api/30_idp_adapter.yaml
Sample deployment: [INTERNAL](https://git.vshn.net/syn-dev/customers/appuio/-/blob/master/c-appuio-control-api-integration.yml#L19).
=> Add IDP adapter deployment

class/defaults.yml, tests/golden/defaults/control-api/control-api/30_idp_adapter.yaml
=> Bump `vshn/appuio-keycloak-adapter` to `v0.5.1`

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/01_role.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/defaults/control-api/control-api/10_rbac_organization.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/01_role.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/10_rbac_organization.yaml
=> Update dependency ghcr.io/appuio/control-api to v0.7.1

docs/modules/ROOT/pages/how-tos/tls.adoc
=> Fix APIService name in how-to

docs/modules/ROOT/pages/references/parameters.adoc
=> Add missing parameter docs for `username_prefix` and `extraArgs`

component/api-controller.jsonnet, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
=> Fix webhook TLS secret reference

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
=> Update appuio/control-api to v0.8.2

class/defaults.yml, component/api-controller.jsonnet, component/api-server.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml
=> Allow passing extra env to apiserver/controller

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/01_countries_configmap.yaml
Switzerland, all countries of the European Union, the United Kingdom, the United States and Canada.
changelog.
=> Extend country list

component/cleanup-cronjob.libsonnet, tests/golden/withcronjob/control-api/control-api/01_api_server/01_countries_configmap.yaml, tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
=> Fix the argument list for the billing entity cleanup job

class/defaults.yml, component/cloud-agent-rbac.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/defaults.yml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_extra-zone-cloud-agent.yaml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrolebinding_extra-zone-cloud-agent.yaml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/v1_secret_extra-zone-cloud-agent.yaml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/v1_serviceaccount_extra-zone-cloud-agent.yaml
Used for RMA0 which is for testing and should not be shown in portal.
Follow up to #93.
changelog.
=> Allow overriding zone ServiceAccount list

class/defaults.yml, tests/golden/defaults/control-api/control-api/30_idp_adapter.yaml, tests/golden/withcronjob/control-api/control-api/30_idp_adapter.yaml
=> Bump `appuio-keycloak-adapter` to `v0.7.1`

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
=> Update control-api to v0.29.1

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/01_role.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/01_role.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/01_role.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
=> Bump `appuio/control-api` to `v0.32.0`

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
=> Bump `appuio/control-api` docker image to `v0.32.1`

class/defaults.yml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-2-cloud-agent.yaml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_extra-zone-cloud-agent.yaml, tests/golden/insecure/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-1-cloud-agent.yaml, tests/golden/withcronjob/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-1-cloud-agent.yaml
=> Update `ghcr.io/appuio/cloud-agent` to `v0.11.0`

class/defaults.yml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-2-cloud-agent.yaml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_extra-zone-cloud-agent.yaml, tests/golden/insecure/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-1-cloud-agent.yaml, tests/golden/withcronjob/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-1-cloud-agent.yaml
=> Update `appuio/cloud-agent` to `v0.12.1`

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
=> Update control-api to `v0.33.1`

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
=> Bump `control-api` to `v0.33.2`

class/defaults.yml, component/api-controller.jsonnet, component/api-server.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml
=> Allow customizing resource requests and limits for API server and controller

class/defaults.yml, tests/golden/defaults/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/defaults/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/insecure/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/insecure/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/01_api_server/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/02_api_controller/02_deployment.yaml, tests/golden/withcronjob/control-api/control-api/20_cronjob.yaml
=> Update `ghcr.io/appuio/control-api` to ` v0.33.3`

class/defaults.yml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-2-cloud-agent.yaml, tests/golden/defaults/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_extra-zone-cloud-agent.yaml, tests/golden/insecure/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-1-cloud-agent.yaml, tests/golden/withcronjob/control-api/control-api/90_cloud_agent_rbac/rbac.authorization.k8s.io_v1_clusterrole_example-zone-1-cloud-agent.yaml
=> Fix appuio-cloud-agent image and bump to v0.20.2

component/main.jsonnet, tests/golden/defaults/control-api/control-api/10_rbac_api_metrics.yaml, tests/golden/insecure/control-api/control-api/10_rbac_api_metrics.yaml, tests/golden/withcronjob/control-api/control-api/10_rbac_api_metrics.yaml
changelog.
- [x ] Categorize the PR by adding one of the labels:
=> Fix metrics rbac and secret
